### ISSUE TITLE
Listings and minted

### ISSUE THREAD

**Issue by yakoum** [yegor256/docshots#5]
Very pleased to use your package.  Is it possible to redefine docshot environment  to use minted or listings ?

**Comment by yegor256** [comment]
@yakoum glad you like the package. How about we do this way:

```
\documentclass{article}
\usepackage[minted=foo]{docshots}
\begin{docshot}
\documentclass{article}
\usepackage{xcolor}
\pagestyle{empty}
\begin{document}
  Hello, {\color{orange}\LaTeX}!
\end{document}
\end{docshot}
\end{document}
```

This `minted=foo` will mean that verbatim text will be rendered as:

```
\inputminted{foo}{file.tex}
```

WDYT?

**Comment by yakoum** [comment]
If you add options: minted and listings?
\usepackage[verbatim=minted,...]{docshots}

**Comment by yegor256** [comment]
@yakoum just `verbatim=minted` is not enough, we need to know the name of the "language" for minted. I suggest:

```
\usepackage[minted=java,...]{docshots}
```

or 

```
\usepackage[lstlisting]{docshots}
```

**Comment by yakoum** [comment]
that's perfect.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`
